---
- name: Set the hostname in /etc/hostname
  shell: echo {{ app.host }} > /etc/hostname
  when: app.host is defined

- name: Set the hostname
  shell: hostname {{ app.host}}
  when: app.host is defined
